---
# defaults file for projectx
project_name: "projectx"
project_directory: "/opt/{{ project_name }}"
src_project_directory: "{{ role_path }}/files/"
compose_files:
  - "{{ project_directory }}/docker-compose.yml"
sync:
  rsync_opts:
    - "--filter=:- .gitignore"
    - "--exclude=.git"
    - "--exclude=logs/"
    - "--exclude=data/"
    - "--exclude=data.tar.gz"
  delete: no
  copy_links: yes
compressed_files:
  - src: data.tar.gz
    dest: "{{ project_directory }}"
    remote_src: no
logging:
  remote_directory: "{{ project_directory }}/logs"
  local_directory: "{{ inventory_dir }}/logs"
  user: root
  group: root
  mode: "0755"
  sources:
    - log_type: "access_combined"
      remote_directory: null
      rsync_opts: []
#        - "--exclude=test"
      rsync_delay_updates: false
    - log_type: "apache_error"
      remote_directory: null
      rsync_opts: []
#        - "--exclude=test"
      rsync_delay_updates: false


# .env.j2 default variables
compose_project_name: "{{ project_name }}"
projectx_image_tag: "2.4-alpine" # "latest"
projectx_image: "httpd:{{ projectx_image_tag }}"
data_dir: "./data"
projectx_http_port: 8080